### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

### ISSUE THREAD

**Issue by oliviaszh** [Currie32/Spell-Checker#14]
I did very similar to the code and I replaced the path by 
path = '/Users/oliviashi/Documents/software/python/books/'

However I cannot run the file because:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

What should I do? Thank you very much!

**Comment by oliviaszh** [comment]
(venv) (Python37) Olivias-MBP:python oliviashi$ python3 /Users/oliviashi/Documents/software/python/DataGenerator.py
Traceback (most recent call last):
  File "/Users/oliviashi/Documents/software/python/DataGenerator.py", line 31, in <module>
    books.append(load_book(path+book))
  File "/Users/oliviashi/Documents/software/python/DataGenerator.py", line 18, in load_book
    book = f.read()
  File "/Users/oliviashi/Documents/software/python/venv/bin/../lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

**Comment by ashupednekar** [comment]
same issue here

**Comment by atishSanyal03** [comment]
just change the line: with open(input_file) as f:
to
with open(input_file, encoding='windows-1252') as f:

**Comment by franzvalo1** [comment]
or you can:

 open(input_file,'rb') as f:
        book = f.read().decode(errors='replace')
