### ISSUE TITLE
I converted the code to TF2.0 but still got error

### ISSUE THREAD

**Issue by iamatsundere** [Currie32/Spell-Checker#18]
Hi, I convert this line 

```
training_logits, _ = tf.contrib.seq2seq.dynamic_decode(training_decoder,
                                                               output_time_major=False,
                                                               impute_finished=True,
                                                               maximum_iterations=max_target_length)
```

into tensorflow 2 format (now, I am using version 2.2.0), and the result is

```
training_logits, _, _ = tfa.seq2seq.decoder.dynamic_decode(decoder=training_decoder,
                                                                   output_time_major=False,
                                                                   impute_finished=True,
                                                                   maximum_iterations=max_target_length,
                                                                   decoder_init_input=dec_embed_input,
                                                                   decoder_init_kwargs={
                                                                       'initial_state': initial_state
                                                                   })
```

However, it still returns error 

```
Traceback (most recent call last):
  File "/home/bayleff/Documents/code/java/spell-checker/bmsc/tryout_x.py", line 637, in <module>
    learning_rate, embedding_size, direction)
  File "/home/bayleff/Documents/code/java/spell-checker/bmsc/tryout_x.py", line 477, in build_graph
    direction)
  File "/home/bayleff/Documents/code/java/spell-checker/bmsc/tryout_x.py", line 403, in seq2seq_model
    direction)
  File "/home/bayleff/Documents/code/java/spell-checker/bmsc/tryout_x.py", line 364, in decoding_layer
    max_target_length)
  File "/home/bayleff/Documents/code/java/spell-checker/bmsc/tryout_x.py", line 299, in training_decoding_layer
    'initial_state': initial_state
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/typeguard/__init__.py", line 840, in wrapper
    retval = func(*args, **kwargs)
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow_addons/seq2seq/decoder.py", line 496, in dynamic_decode
    swap_memory=swap_memory,
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2491, in while_loop_v2
    return_same_structure=True)
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2688, in while_loop
    back_prop=back_prop)
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow/python/ops/while_v2.py", line 196, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow/python/ops/while_v2.py", line 174, in wrapped_body
    outputs = body(*_pack_sequence_as(orig_loop_vars, args))
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow_addons/seq2seq/decoder.py", line 401, in body
    time, inputs, state, training
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow_addons/seq2seq/basic_decoder.py", line 135, in step
    cell_outputs, cell_state = self.cell(inputs, state, training=training)
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 265, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/bayleff/Documents/code/pyvenv/lib/python3.6/site-packages/tensorflow_addons/seq2seq/attention_wrapper.py:2048 call  *
        cell_output, next_cell_state = self._cell(cell_inputs, cell_state, **kwargs)

    TypeError: __call__() got an unexpected keyword argument 'training'
```

Please help me, thank you!

**Comment by fzehracetin** [comment]
For anyone who is trying to convert to the Tensorflow version 2.0, `tfa.seq2seq.AttentionWrapper` is not expected to work with `tf.compat.v1` modules. Look at the Tensorflow/Addons repo: [#2383](https://github.com/tensorflow/addons/issues/2383#issuecomment-776622620)
